### ISSUE TITLE
Create Project Workflow 

### ISSUE THREAD

**Issue by junwooYeom** [Compose-Picker/Picker#12]
### 🔍️ Description

- create Automation with Issue & Pull request

### 📌 Tasks 

- [ ] Todo part
- [ ] In  Progress part
- [ ] In Pr part
- [ ] Ready To Release part
- [ ] Released part
