### ISSUE TITLE
Create Sample

### ISSUE THREAD

**Issue by ghost** [Compose-Picker/Picker#18]
### 🔍️ Description

- Create Sample Application of Date Picker and Time Picker

  

### 📌 Tasks 

- [ ] Create Date Picker Application
- [ ] Create Time Picker Application
- [ ] Add descriptions to provide how to use and critical parameters
